### ISSUE TITLE
Progress Notifications

### ISSUE THREAD

**Issue by ccoupe** [FriedCheese2006/BambuLabs#1]
Hi 
  As I mentioned in the Hubitat forum, I might submit a pull request.  It turns out that pull requests are harder than I want to deal with. I've included a link to the diff's so you can see what was done for notifications. 
  I also decided to see if state variables would allow me to not use the subscribe/unsubscribe and not get too many events flagged by hubitat. Seems to work, so far.

[Progress Notifications](https://github.com/ccoupe/BambuLabs/commit/c86c42022db92a54f3bb84b9ed391d068da4f170)
[State Vars](https://github.com/ccoupe/BambuLabs/commit/4e3f71b03352e644717416e1bd151130ebeff697)

**Comment by FriedCheese2006** [comment]
Not integrated.
